name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2

    - name: Setup python 
      uses: actions/setup-python@v2
    
    - name: Setup conan 
      run: |
        # python -m venv venv
        # source venv/bin/activate
        pip install conan
        mkdir build
        cd build
        conan user
        conan install ..
 
    - name: Configure
      run: |
        cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Debug

    - name: Build
      run: |
        cmake --build build --config Debug



 
         
