name: Linux

on: [push]

jobs:
  build:
  
    defaults:
      run:
        shell: bash -l {0}

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: |
        sudo apt-get install xorg-dev
        sudo apt-get install freeglut3-dev        
    - name: Setup conan 
      run: |
        pip3 install wheel setuptools
        pip3 install conan --upgrade

    - name: Build
      run: |
        mkdir build && cd build
        conan install .. --build=missing -s compiler.libcxx=libstdc++11
        cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
        cmake --build .

      -name: Test
        ctest 
