name: Linux

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: |
        sudo apt-get install xorg-dev
        sudo apt-get install freeglut3-dev        
    - name: Setup conan 
      run: |
        python -m venv venv
        source venv/bin/activate
        pip3 install wheel setuptools
        pip3 install conan --upgrade
        mkdir build
        cd build
        conan install .. --build=missing -s compiler.libcxx=libstdc++11
    - name: Build
      run: |
        cd build
        cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
        cmake --build .
