name: macOS

on: [push]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
       
    - name: Setup conan 
      run: |
        brew install conan

    - name: Build
      run: |
        cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release
        cmake --build build --config Release
