name: macOS

on: [push]

jobs:
  build:
  
    defaults:
      run:
        shell: bash -l {0}

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
       
    - name: Setup conan 
      run: |
        # python -m venv venv
        # source venv/bin/activate
        pip3 install wheel setuptools
        pip3 install conan --upgrade

    - name: Build
      run: |
        mkdir build && cd build
        conan install .. #--build=missing -s compiler.libcxx=libstdc++
        cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
        cmake --build .
