name: Windows

on: [push]

jobs:
  build:
        
    runs-on: windows-latest
   
    steps:
    - uses: actions/checkout@v1     
    - name: install conan
      run: pipx install conan 
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cmake --build . --config Release
    - name: test
      run: cd build && ctest
